BASE_URL: ""
AUTH_TOKEN_TTL: ""
PROJECT_NAME: ""

#facebook
# FACEBOOK_APP_ID: "1602325316491451"
# FACEBOOK_SECRET: "154c907122f3bea62046bf4ea68d2575"
FACEBOOK_APP_ID: ""
FACEBOOK_SECRET: ""

#twitter
TWITTER_KEY: ""
TWITTER_SECRET: ""

#google
GOOGLE_CLIENT_ID: ""
GOOGLE_CLIENT_SECRET: ""

#firebase
# FIREBASE_API_KEY: "AIzaSyAPt1rBSGDplz8wgsoWtkfUYvSglc9lygQ"
FIREBASE_API_KEY: ""
